Vagrant.configure('2') do |config|
  config.vm.box_download_insecure = true
  config.ssh.insert_key = false

  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.auto_detect = true
    # config.cache.scope = :machine
    config.cache.scope = :box
    config.cache.enable :chef
    config.cache.enable :apt
    config.cache.enable :yum
    config.cache.enable :gem
  end

  if Vagrant.has_plugin?('vagrant-omnibus')
    # chef_omnibus_install_options = '-d /tmp/vagrant-cache/vagrant_omnibus'
    config.omnibus.cache_packages = true
  end

  if Vagrant.has_plugin?('vagrant-proxyconf')
    if ENV['http_proxy']
      # puts 'http_proxy: ' + ENV['http_proxy']
      config.proxy.http = ENV['http_proxy']
    end
    if ENV['https_proxy']
      # puts 'https_proxy: ' + ENV['https_proxy']
      config.proxy.https = ENV['https_proxy']
    end
    if ENV['no_proxy']
      # puts 'no_proxy: ' + ENV['no_proxy']
      config.proxy.no_proxy = ENV['no_proxy']
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'on']
  end

  if Vagrant.has_plugin?('vagrant-vbguest')
    config.vbguest.auto_update = false
    config.vbguest.no_remote = false
  end
end

# if Vagrant.has_plugin?('vagrant-winrm')
#   config.winrm.username = 'vagrant'
#   config.winrm.password = 'vagrant'
#   config.winrm.port = 5985
#   config.winrm.guest_port = 5985
#   config.winrm.winrm_transport = 'ssl'
# end
